"""empty message

Revision ID: 46613cdd3c7f
Revises: 278f37380218
Create Date: 2021-01-30 10:44:39.837844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46613cdd3c7f'
down_revision = '278f37380218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
